apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-05T19:44:01Z"
  name: shopping-cart
  namespace: corey4
  resourceVersion: "70336910"
  selfLink: /api/v1/namespaces/corey4/services/shopping-cart
  uid: a98404f2-5f19-11ea-9053-4201ac100108
spec:
  clusterIP: 10.12.58.3
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8013
  selector:
    app.kubernetes.io/name: shopping-cart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
