apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-06T00:21:31Z"
  name: shopping-cart2
  namespace: corey4
  ownerReferences:
  resourceVersion: "70465946"
  selfLink: /api/v1/namespaces/corey4/services/shopping-cart2  
spec:
  clusterIP: 10.13.101.94
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8013
  selector:
    app.kubernetes.io/name: shopping-cart2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
