# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: shopping-cart
spec:
  # Datastore configuration
  storeConfig:
    database: shopping
    statefulStore:
      # Name of a deployed Datastore to use.
      name: shopping-store
  containers:
    - image: lightbend-docker-registry.bintray.io/cloudstate-samples/shopping-cart:latest
      name: js-shopping-cart
